/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import basededatos.basededatos;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Familia
 */
public class inic_usua extends javax.swing.JFrame {

    /**
     * Creates new form inic_usua
     */
    public inic_usua() {
        initComponents();
        this.setTitle("Sistema de informacion hospitalaria");
        this.setLocation(400, 100);
        this.setSize(520,460);
        this.setResizable(false);
    
        initComponents();
       
        fiel_user.requestFocus();
       
    }
    void acceder(String usuario, String pass)// metodo para acceder de un nuevo usuario de bd
    {
        String cap="";//creacion de varibles que mira el tipo de usuario que es 
       String sql="SELECT * FROM tab_usua WHERE nick_usua='"+usuario+"' && pass_usua='"+pass+"'";//busca en la bd la informacion 
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);//
            while(rs.next())// valida que los datos esten en la bd
            {
                cap=rs.getString("tap_usua");// mira el tipo de usuario 
            }
            if(cap.equals("ADMINISTRADOR"))// si es este tipo lo direcciona 
            {
                  this.setVisible(false);
                    JOptionPane.showMessageDialog(null, "BIENVENIDO");
                     menu_admi ingreso = new menu_admi();
                    ingreso.setVisible(true);
                    ingreso.pack();
            }
             if(cap.equals("PACIENTE"))// si es de este tipo direcciona a la venta de paciente 
            {
                  this.setVisible(false);
                    JOptionPane.showMessageDialog(null, "BIENVENIDO");
                     menu_paci ingreso = new menu_paci();
                    ingreso.setVisible(true);
                    ingreso.pack();
            }
            if(cap.equals("DOCTOR"))// si es de este tipo lo direcciona a la ventana de doctor 
            {
            this.setVisible(false);
                    JOptionPane.showMessageDialog(null, "BIENVENIDO");
                     menu_doct ingresos = new menu_doct();
                    ingresos.setVisible(true);
                    ingresos.pack();
                    
            }
            if((!cap.equals("ADMINISTRADOR"))&& (!cap.equals("DOCTOR"))&& (!cap.equals("PACIENTE"))) // valida que aparezcan si no aparecen 
            {
                JOptionPane.showMessageDialog(this, "LOS DATOS ESTAN INCORRECTOS");// este es el mensaje que le aparece 
            }
        } catch (SQLException ex) {
            Logger.getLogger(inic_usua.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labe_pass = new javax.swing.JLabel();
        labe_user = new javax.swing.JLabel();
        fiel_user = new javax.swing.JTextField();
        boto_limp = new javax.swing.JButton();
        boto_envi = new javax.swing.JButton();
        boto_regr = new javax.swing.JButton();
        labe_titu = new javax.swing.JLabel();
        fiel_pass = new javax.swing.JPasswordField();
        labe_inic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labe_pass.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        labe_pass.setForeground(new java.awt.Color(255, 255, 255));
        labe_pass.setText("Contraseña de usuario:");
        getContentPane().add(labe_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 150, 30));

        labe_user.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        labe_user.setForeground(new java.awt.Color(255, 255, 255));
        labe_user.setText("Nombre de usuario:");
        getContentPane().add(labe_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 130, 30));

        fiel_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiel_userActionPerformed(evt);
            }
        });
        getContentPane().add(fiel_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 210, 30));

        boto_limp.setBackground(new java.awt.Color(0, 153, 153));
        boto_limp.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        boto_limp.setForeground(new java.awt.Color(255, 255, 255));
        boto_limp.setText("Limpiar");
        boto_limp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boto_limpActionPerformed(evt);
            }
        });
        getContentPane().add(boto_limp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 110, 40));

        boto_envi.setBackground(new java.awt.Color(0, 153, 153));
        boto_envi.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        boto_envi.setForeground(new java.awt.Color(255, 255, 255));
        boto_envi.setText("Enviar");
        boto_envi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boto_enviActionPerformed(evt);
            }
        });
        getContentPane().add(boto_envi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 110, 40));

        boto_regr.setBackground(new java.awt.Color(0, 153, 153));
        boto_regr.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        boto_regr.setForeground(new java.awt.Color(255, 255, 255));
        boto_regr.setText("Regresar");
        boto_regr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boto_regrActionPerformed(evt);
            }
        });
        getContentPane().add(boto_regr, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 110, 40));

        labe_titu.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        labe_titu.setForeground(new java.awt.Color(255, 255, 255));
        labe_titu.setText("Iniciar sesion como usuario");
        getContentPane().add(labe_titu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 240, 70));
        getContentPane().add(fiel_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 210, 30));

        labe_inic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/img3.jpg"))); // NOI18N
        getContentPane().add(labe_inic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fiel_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiel_userActionPerformed
     fiel_user.requestFocus();
    }//GEN-LAST:event_fiel_userActionPerformed

    private void boto_limpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boto_limpActionPerformed
     fiel_user.setText(null);
     fiel_pass.setText(null);
    }//GEN-LAST:event_boto_limpActionPerformed

    private void boto_enviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boto_enviActionPerformed
     String usu=fiel_user.getText();
    String pas=new String(fiel_pass.getPassword());
    acceder(usu, pas);
    }//GEN-LAST:event_boto_enviActionPerformed

    private void boto_regrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boto_regrActionPerformed
            menu_prin regu = new menu_prin();
            regu.setVisible(true);
            regu.pack();
             this.dispose();
    }//GEN-LAST:event_boto_regrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inic_usua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inic_usua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inic_usua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inic_usua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inic_usua().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boto_envi;
    private javax.swing.JButton boto_limp;
    private javax.swing.JButton boto_regr;
    private javax.swing.JPasswordField fiel_pass;
    private javax.swing.JTextField fiel_user;
    private javax.swing.JLabel labe_inic;
    private javax.swing.JLabel labe_pass;
    private javax.swing.JLabel labe_titu;
    private javax.swing.JLabel labe_user;
    // End of variables declaration//GEN-END:variables
      basededatos cc = new basededatos();
Connection cn = cc.Conectar();

}
