/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Dimension;

/**
 *
 * @author Familia
 */
public class menu_paci extends javax.swing.JFrame {

    /**
     * Creates new form menu_prin
     */
    public menu_paci() {
        initComponents();
        this.setTitle("Sistema de informacion hospitalaria");
        this.setLocation(400, 100);
        this.setSize(510,530);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boto_asig = new javax.swing.JButton();
        boto_canc = new javax.swing.JButton();
        boto_cons = new javax.swing.JButton();
        boto_hist = new javax.swing.JButton();
        boto_cier = new javax.swing.JButton();
        labe_titu = new javax.swing.JLabel();
        labe_menu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boto_asig.setBackground(new java.awt.Color(0, 153, 153));
        boto_asig.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        boto_asig.setForeground(new java.awt.Color(255, 255, 255));
        boto_asig.setText("Asignar una nueva cita medica");
        boto_asig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boto_asigActionPerformed(evt);
            }
        });
        getContentPane().add(boto_asig, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 300, 50));

        boto_canc.setBackground(new java.awt.Color(0, 153, 153));
        boto_canc.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        boto_canc.setForeground(new java.awt.Color(255, 255, 255));
        boto_canc.setText("Cancelar una cita medica");
        boto_canc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boto_cancActionPerformed(evt);
            }
        });
        getContentPane().add(boto_canc, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 300, 50));

        boto_cons.setBackground(new java.awt.Color(0, 153, 153));
        boto_cons.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        boto_cons.setForeground(new java.awt.Color(255, 255, 255));
        boto_cons.setText("Consultar una cita medica");
        boto_cons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boto_consActionPerformed(evt);
            }
        });
        getContentPane().add(boto_cons, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 300, 50));

        boto_hist.setBackground(new java.awt.Color(0, 153, 153));
        boto_hist.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        boto_hist.setForeground(new java.awt.Color(255, 255, 255));
        boto_hist.setText("Descargar copia de historial medico");
        boto_hist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boto_histActionPerformed(evt);
            }
        });
        getContentPane().add(boto_hist, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 300, 50));

        boto_cier.setBackground(new java.awt.Color(0, 153, 153));
        boto_cier.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        boto_cier.setForeground(new java.awt.Color(255, 255, 255));
        boto_cier.setText("Cerrar sesion");
        boto_cier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boto_cierActionPerformed(evt);
            }
        });
        getContentPane().add(boto_cier, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 140, 50));

        labe_titu.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        labe_titu.setForeground(new java.awt.Color(255, 255, 255));
        labe_titu.setText("Bienvenido, seleccione una opcion para continuar");
        getContentPane().add(labe_titu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 450, 70));

        labe_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/img3.jpg"))); // NOI18N
        labe_menu.setMinimumSize(null);
        getContentPane().add(labe_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boto_asigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boto_asigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boto_asigActionPerformed

    private void boto_cancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boto_cancActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boto_cancActionPerformed

    private void boto_consActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boto_consActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boto_consActionPerformed

    private void boto_histActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boto_histActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boto_histActionPerformed

    private void boto_cierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boto_cierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boto_cierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_paci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_paci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_paci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_paci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_paci().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boto_asig;
    private javax.swing.JButton boto_canc;
    private javax.swing.JButton boto_cier;
    private javax.swing.JButton boto_cons;
    private javax.swing.JButton boto_hist;
    private javax.swing.JLabel labe_menu;
    private javax.swing.JLabel labe_titu;
    // End of variables declaration//GEN-END:variables
}
