/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import basededatos.basededatos;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Familia
 */
public class regi_usua extends javax.swing.JFrame {

    /**
     * Creates new form regi_usua
     */
    public regi_usua() {
        initComponents();
        this.setTitle("Sistema de informacion hospitalaria");
        this.setLocation(400, 100);
        this.setSize(580,550);
        this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labe_iden = new javax.swing.JLabel();
        labe_nomb = new javax.swing.JLabel();
        labe_corr = new javax.swing.JLabel();
        labe_apel = new javax.swing.JLabel();
        labe_user = new javax.swing.JLabel();
        labe_pass = new javax.swing.JLabel();
        fiel_nomb = new javax.swing.JTextField();
        fiel_apel = new javax.swing.JTextField();
        fiel_iden = new javax.swing.JTextField();
        fiel_corr = new javax.swing.JTextField();
        fiel_user = new javax.swing.JTextField();
        boto_regr = new javax.swing.JButton();
        boto_envi = new javax.swing.JButton();
        boto_limp = new javax.swing.JButton();
        labe_titu = new javax.swing.JLabel();
        fiel_tipo = new javax.swing.JComboBox();
        labe_corr1 = new javax.swing.JLabel();
        fiel_pass = new javax.swing.JPasswordField();
        labe_regi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labe_iden.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        labe_iden.setForeground(new java.awt.Color(255, 255, 255));
        labe_iden.setText("Numero de Identificacion: ");
        getContentPane().add(labe_iden, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 160, 40));

        labe_nomb.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        labe_nomb.setForeground(new java.awt.Color(255, 255, 255));
        labe_nomb.setText("Nombres: ");
        getContentPane().add(labe_nomb, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 70, 40));

        labe_corr.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        labe_corr.setForeground(new java.awt.Color(255, 255, 255));
        labe_corr.setText("Tipo de usuario");
        getContentPane().add(labe_corr, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 120, 40));

        labe_apel.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        labe_apel.setForeground(new java.awt.Color(255, 255, 255));
        labe_apel.setText("Apellidos: ");
        getContentPane().add(labe_apel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 70, 40));

        labe_user.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        labe_user.setForeground(new java.awt.Color(255, 255, 255));
        labe_user.setText("Nombre de usuario:");
        getContentPane().add(labe_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 130, 40));

        labe_pass.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        labe_pass.setForeground(new java.awt.Color(255, 255, 255));
        labe_pass.setText("Contraseña de usuario:");
        getContentPane().add(labe_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 150, 40));

        fiel_nomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiel_nombActionPerformed(evt);
            }
        });
        fiel_nomb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fiel_nombKeyTyped(evt);
            }
        });
        getContentPane().add(fiel_nomb, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 210, 30));

        fiel_apel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiel_apelActionPerformed(evt);
            }
        });
        fiel_apel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fiel_apelKeyTyped(evt);
            }
        });
        getContentPane().add(fiel_apel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 210, 30));

        fiel_iden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiel_idenActionPerformed(evt);
            }
        });
        fiel_iden.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fiel_idenKeyTyped(evt);
            }
        });
        getContentPane().add(fiel_iden, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 210, 30));

        fiel_corr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiel_corrActionPerformed(evt);
            }
        });
        getContentPane().add(fiel_corr, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 210, 30));

        fiel_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiel_userActionPerformed(evt);
            }
        });
        getContentPane().add(fiel_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 210, 30));

        boto_regr.setBackground(new java.awt.Color(0, 153, 153));
        boto_regr.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        boto_regr.setForeground(new java.awt.Color(255, 255, 255));
        boto_regr.setText("Regresar");
        boto_regr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boto_regrActionPerformed(evt);
            }
        });
        getContentPane().add(boto_regr, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 110, 40));

        boto_envi.setBackground(new java.awt.Color(0, 153, 153));
        boto_envi.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        boto_envi.setForeground(new java.awt.Color(255, 255, 255));
        boto_envi.setText("Enviar");
        boto_envi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boto_enviActionPerformed(evt);
            }
        });
        getContentPane().add(boto_envi, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 110, 40));

        boto_limp.setBackground(new java.awt.Color(0, 153, 153));
        boto_limp.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        boto_limp.setForeground(new java.awt.Color(255, 255, 255));
        boto_limp.setText("Limpiar");
        boto_limp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boto_limpActionPerformed(evt);
            }
        });
        getContentPane().add(boto_limp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 110, 40));

        labe_titu.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        labe_titu.setForeground(new java.awt.Color(255, 255, 255));
        labe_titu.setText("Registro de un usuario nuevo");
        getContentPane().add(labe_titu, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 260, 60));

        fiel_tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "DOCTOR", "PACIENTE", "ADMINISTRADOR" }));
        fiel_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiel_tipoActionPerformed(evt);
            }
        });
        getContentPane().add(fiel_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 210, 30));

        labe_corr1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        labe_corr1.setForeground(new java.awt.Color(255, 255, 255));
        labe_corr1.setText("Correo electronico: ");
        getContentPane().add(labe_corr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 120, 40));
        getContentPane().add(fiel_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 210, 30));

        labe_regi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/img3.jpg"))); // NOI18N
        getContentPane().add(labe_regi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fiel_nombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiel_nombActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fiel_nombActionPerformed

    private void fiel_apelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiel_apelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fiel_apelActionPerformed

    private void fiel_idenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiel_idenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fiel_idenActionPerformed

    private void fiel_corrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiel_corrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fiel_corrActionPerformed

    private void fiel_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiel_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fiel_userActionPerformed

    private void boto_limpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boto_limpActionPerformed
     fiel_nomb.setText(null);
     fiel_apel.setText(null);
     fiel_iden.setText(null);
     fiel_corr.setText(null);
     fiel_user.setText(null);
     fiel_pass.setText(null);
    }//GEN-LAST:event_boto_limpActionPerformed

    private void fiel_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiel_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fiel_tipoActionPerformed

    private void boto_enviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boto_enviActionPerformed
         basededatos mysql=new basededatos(); // mira la bd 
         com.mysql.jdbc.Connection cn =mysql.Conectar();// se conecta con el campo de mysql 
         String nom,apel,iden,cor,tipo,usu,contra;// se crea variables
         String sSql="";
         String mensaje="";
         nom=fiel_nomb.getText();
         apel=fiel_apel.getText();
         iden=fiel_iden.getText();
         cor=fiel_corr.getText();
         tipo=fiel_tipo.getSelectedItem().toString();// esto es para lo que escriba aca se lleve a la bd
         usu=fiel_user.getText();
         contra=fiel_pass.getText();
             if (fiel_nomb.getText().equals("") || (fiel_apel.getText().equals("")) || (fiel_iden.getText().equals("")) || (fiel_corr.getText().equals(""))
            || (fiel_tipo.getSelectedItem().equals(""))|| (fiel_user.getText().equals("")) || (fiel_pass.getText().equals(""))) {
       javax.swing.JOptionPane.showMessageDialog(this,"Debe llenar todos los campos \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            fiel_nomb.requestFocus();   }// aca es una validacion para decir que los campos tiene que ser llenados 

             else {
        String sSQL = "INSERT INTO tab_usua (nomb_paci, apel_paci, primer_apellido,segundo_apellido,tipo_de_documento, numero_de_documento , direccion, tipo_usuario, id_usuario, contraseña)"+"values(?,?,?,?,?,?,?)";
         mensaje="los datos se han insertado de manera satisfacria ";// aca esta guardando los datos en la bd
         try {
           PreparedStatement pat = cn.prepareStatement(sSQL);
           pat.setString(1, nom);
           pat.setString(2, apel);
           pat.setString(3, iden);
           pat.setString(4, cor);
           pat.setString(5, tipo);
           pat.setString(6, usu);
           pat.setString(7, contra);
           
           int n=pat.executeUpdate();
           if (n>0)
           {
           JOptionPane.showMessageDialog(null, mensaje);
           }
       }
       catch(SQLException ex){
            inic_usua regu = new inic_usua();
            regu.setVisible(true);
            regu.pack();
            this.dispose();
JOptionPane.showMessageDialog(null, ex);
}   
       
    }                                        
          
    }//GEN-LAST:event_boto_enviActionPerformed

    private void boto_regrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boto_regrActionPerformed
      menu_prin regu = new menu_prin();
            regu.setVisible(true);
            regu.pack();
            this.dispose();
    }//GEN-LAST:event_boto_regrActionPerformed

    private void fiel_nombKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fiel_nombKeyTyped
      char c = evt.getKeyChar();
        if((c<'a' || c>'z')  && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();// valida que solo se pueda escribir letras

    }//GEN-LAST:event_fiel_nombKeyTyped

    private void fiel_apelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fiel_apelKeyTyped
     char c = evt.getKeyChar();
        if((c<'a' || c>'z')  && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();// valida que solo se pueda escribir letras

    }//GEN-LAST:event_fiel_apelKeyTyped

    private void fiel_idenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fiel_idenKeyTyped
             char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();// valida que solo se pueda escribir numeros 
    }//GEN-LAST:event_fiel_idenKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regi_usua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regi_usua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regi_usua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regi_usua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regi_usua().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boto_envi;
    private javax.swing.JButton boto_limp;
    private javax.swing.JButton boto_regr;
    private javax.swing.JTextField fiel_apel;
    private javax.swing.JTextField fiel_corr;
    private javax.swing.JTextField fiel_iden;
    private javax.swing.JTextField fiel_nomb;
    private javax.swing.JPasswordField fiel_pass;
    private javax.swing.JComboBox fiel_tipo;
    private javax.swing.JTextField fiel_user;
    private javax.swing.JLabel labe_apel;
    private javax.swing.JLabel labe_corr;
    private javax.swing.JLabel labe_corr1;
    private javax.swing.JLabel labe_iden;
    private javax.swing.JLabel labe_nomb;
    private javax.swing.JLabel labe_pass;
    private javax.swing.JLabel labe_regi;
    private javax.swing.JLabel labe_titu;
    private javax.swing.JLabel labe_user;
    // End of variables declaration//GEN-END:variables
}
